手动识别页面增加分页功能
NAStool/nas-tools pull request #3498
Opened 2023-02-13 09:33 UTC by HateBaozi

对应issue https://github.com/NAStool/nas-tools/issues/3453

2023-02-13 10:44 UTC, 120318 commented
需要提到 dev 分支。

2023-02-13 12:15 UTC, jxxghp requested changes

2023-02-13 12:15 UTC, jxxghp commented on web/templates/rename/unidentification.html
> +    navmenu("history?page=" + (page - 1))
页面错误

2023-02-13 14:59 UTC, HateBaozi commented on web/templates/rename/unidentification.html
> +    navmenu("history?page=" + (page - 1))
已修改，同时改为提交到dev分支

2023-02-14 05:54 UTC, fsffsfs commented
最新版为啥内建索引器 RARBG那些不见了？？。，。

2023-02-14 07:52 UTC, merged