Dev
NAStool/nas-tools pull request #3830
Opened 2023-03-14 18:22 UTC by Sowevo

下载器监控增加目录隔离
<img width="746" alt="image" src="https://user-images.githubusercontent.com/31763582/225101146-17864a55-547e-41f5-b6e5-89e516259379.png">

2023-03-14 18:28 UTC, Sowevo commented
避免下载器监控时...刮削一些奇怪的目录(学习资料)

2023-03-15 02:22 UTC, thofx commented
> 避免下载器监控时...刮削一些奇怪的目录(学习资料)

我可以看看你的学习资料吗

2023-03-15 05:08 UTC, jxxghp requested changes

2023-03-15 05:08 UTC, jxxghp commented on app/downloader/client/_base.py
> +            if os.path.commonpath([directory['save_path'], path]) == directory['save_path']:
需要加上异常捕捉

2023-03-15 05:08 UTC, jxxghp commented on app/downloader/client/qbittorrent.py
> +    def get_transfer_task(self, tag, match_path):
新加参数建议赋默认值为None

2023-03-15 05:08 UTC, jxxghp commented on app/downloader/client/transmission.py
> +    def get_transfer_task(self, tag, match_path):
默认值None

2023-03-15 09:01 UTC, merged