feat 转移历史、删种支持删除转种和辅种
NAStool/nas-tools pull request #4227
Opened 2023-04-10 07:00 UTC by thsrite

[TORRENT_TRANSFER_HISTORY.zip](https://github.com/NAStool/nas-tools/files/11188357/TORRENT_TRANSFER_HISTORY.zip)
新建了个表，我不知道如何在代码里新增。。

想法是，转种插件转种完成插入一条历史记录。

删种的时候判断当前下载器的这个种子hash是否已经转种
1.未转种，则按照以前逻辑走
2.转种了，①删除源种子文件，则直接删除目标下载器的目标种子；②未删除源种子文件，则转种前后下载器都删除

辅种的话，只处理开启了iyuu辅种插件且填写token的情况。
1.根据要删除种子的hash去iyuu获取所有的可辅种hash
2.查询上述下载器中是否存在该种子，存在则删除  （默认为查询默认下载器是否有辅种，如果转种了，则查询转种下载器中是否有辅种）

2023-04-10 07:15 UTC, jxxghp commented
从插件的角度来讲，涉及到加表就有点重了。

2023-04-10 08:07 UTC, thsrite commented
> 从插件的角度来讲，涉及到加表就有点重了。

是有点。我在转种插件加了个字段，字典类型。
key=下载器id-源种子hash
value={
目标下载器,
目标种子,
是否删除源种子
}

2023-04-10 08:11 UTC, thsrite commented
主要是默认下载器下载，
每天先转种插件转到tr。
再辅种插件tr辅种。

如果emby看完了，想删除的话，通过emby同步删除插件触发nt删除历史记录及源文件，下载任务。
如何能删除转种和辅种的话，就一步到位了--

等自动删种处理的话，我总担心源文件被删除了被认为做假种，虽然也可以设置自动删种频率解决...

2023-04-10 11:29 UTC, thsrite commented
#4186

2023-04-10 14:55 UTC, jxxghp commented
会导致配置越来起大。
我看看怎么提供一个公共的机制，让插件可以记录和查询历史数据吧。

2023-04-11 00:29 UTC, jxxghp requested changes
已支持插件运行数据记录和查询，请修改适配。

2023-04-11 01:22 UTC, closed without merging