RSS订阅加入快速匹配选项和功能
NAStool/nas-tools pull request #4452
Opened 2023-04-21 21:00 UTC by sjh00

RSS中抬头含中文名称副标题时快速识别匹配，减少重新查询TMDB次数，提升效率和资源，节省大量时间，仅在设置RSS时标题设置勾选副标题时推荐使用

2023-04-22 05:37 UTC, Shurelol commented
Tmdb查询有做缓存

实际rss只会识别相比上次增加的种子

2023-04-22 06:58 UTC, sjh00 commented
> Tmdb查询有做缓存
> 
> 实际rss只会识别相比上次增加的种子

每次点“电影/电视剧订阅”服务，我看日志里都是全部识别一遍，我设置的站点多，每个站都是50条订阅，订阅返回的种子有新有旧，TMDB缓存过期的还是会重新拉取一遍，每一条都访问TMDB真的很慢。我加的这个功能亲测实际使用非常快，不会有误差，因为是利用关键字检索快速预匹配，预匹配成功后还是走原先流程拉取TMDB，预匹配不成功就不处理循环下一个，节省本来就不匹配的种还要拉取TMDB浪费的时间，而且这样RSS种子抬头如果不规范或是不含作品名的“杂种”，我也不想要，可以避免浪费时间去拉取TMDB获得错误信息。

2023-04-22 09:51 UTC, git-0101 commented
在站点没有新增种子的情况下，日志里还是显示获取之前相同的种子数，也有处理的记录。能否只显示新增数量的种子。

2023-04-22 23:34 UTC, jxxghp requested changes
跟现在订阅选项里的模糊匹配区别是？

2023-04-23 03:08 UTC, sjh00 commented
> 跟现在订阅选项里的模糊匹配区别是？

现在订阅选项里的模糊匹配也是先拉取TMDB，格式化后再进行比较

**现在流程：**
识别种子名称 -> 搜索TMDB或缓存 -> 检查种子是否匹配订阅 -> 判断是否模糊匹配

**加入预匹配后流程：**
识别种子名称 -> 快速预匹配 -成功->搜索TMDB或缓存 -> 检查种子是否匹配订阅 -> 判断是否模糊匹配

因为搜索TMDB或缓存耗时较多，且会占用大量访问接口资源，在配置网站RSS抬头勾选副标题的情况下，种子标题含作品中文名称，正好可以用订阅中文名比较种子标题，明显不匹配的直接跳过，不再搜索TMDB或缓存。

ps：我在订阅中文名比较种子标题这里，对作品名中含有符号（，：！·等）的情况进行了处理，以预防同一作品订阅名和种子标题中符号一个是中文符号另一个是英文符号的情况
ps：后提交的558ea0a对现有的rss.py中两处判断比较方式进行了修正，原[if not re.search(name, search_title, re.I) and name not in search_title]判断，若name含有正则匹配特殊字符，会导致匹配错误，改为转小写if in比较

2023-04-23 03:15 UTC, sjh00 commented
> 在站点没有新增种子的情况下，日志里还是显示获取之前相同的种子数，也有处理的记录。能否只显示新增数量的种子。

日志里倒是影响不大，我更想让nas-tools专开一页展示聚合后的RSS列表页面，设置过期时间，方便我从一个页面看所有站点的最新种😂

2023-04-23 03:21 UTC, jxxghp commented
原来的模糊匹配初衷就是这样，但是因为用的人太少，后面也没再关注，改了多版后出问题了。
如果需要，应基于现有逻辑优化，不应再增加设置项。

2023-04-23 03:21 UTC, closed without merging